### ISSUE TITLE
Jenkins 환경

### ISSUE THREAD

**Issue by Jeonghoon2** [encore-PR4/chat-server#11]
# Jenkins Excute Shell
> env
<img width="663" alt="image" src="https://github.com/user-attachments/assets/e964f880-cae3-4e17-8672-c605c1d548e7">
<img width="663" alt="스크린샷 2024-10-26 오전 1 07 42" src="https://github.com/user-attachments/assets/a4e4f1b6-b679-4c09-bbe6-3e4999922ff8">

# Spring Boot Build Cycle

> prod 환경 기준
- start-prod.sh
```sh
#!/bin/bash

SERVER_NAME=codulki
DOCKER_COMPOSE_FILE=docker-compose.prod.yml

# ./gradlew clean & ./gradlew build 를 여기에 넣을지 말지 고민중
# 어떤 영향이 없는지 고민 중

# 기존 서버 및 데이터베이스 컨테이너 종료 및 제거
echo "기존 서버 및 데이터베이스 컨테이너를 종료하고 제거합니다."
docker-compose -f $DOCKER_COMPOSE_FILE down

# 도커 컴포즈로 이미지를 캐시 없이 빌드
echo "캐시 없이 도커 이미지를 빌드합니다."
docker-compose -f $DOCKER_COMPOSE_FILE build

# 도커 컴포즈로 새로운 서버 및 데이터베이스 컨테이너 실행
echo "새로운 도커 컴포즈 컨테이너를 시작합니다."
docker-compose -f $DOCKER_COMPOSE_FILE up -d

# 서버 컨테이너의 실행 상태 확인
echo "서버 컨테이너의 상태를 검사합니다."
if [ "$(docker inspect -f '{{.State.Running}}' $SERVER_NAME 2>/dev/null)" = "true" ]; then
  echo "서버 컨테이너가 성공적으로 실행 중입니다."
else
  echo "서버 컨테이너 실행에 실패했습니다."
fi

```
- docker-compose.prod.yml
```
version: '3.8'

services:
  server:
    build: .
    image: codulki:0.0.1
    container_name: codulki
    ports:
      - "7777:8080"
    depends_on:
      - database

  database:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: codulki
      MYSQL_USER: codulki
      MYSQL_PASSWORD: codul123
    ports:
      - "3306:3306"
    volumes:
      - /home/ubuntu/data/db:/var/lib/mysql
```
